name: ESP-IDF v5.3

on:
  push:
    branches: []
  pull_request:
    branches: []
  schedule:
    - cron: "0 1 * * 6" # Every Saturday at 1AM  

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
    
jobs:

  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["v5.3.3"]
        idf_target: ["esp32"]
  
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/app

      - name: Compile
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
          path: app/examples/esp-idf
          command: apt-get update && apt-get install -y python3-venv && idf.py build