name: Platform IO

on:
  push:
    branches: []
  pull_request:
    branches: []
  schedule:
    - cron: "0 1 * * 6" # Every Saturday at 1AM  

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - example: platformio
          board: esp32dev

    runs-on: ubuntu-latest
    name: Build ${{ matrix.example }}-${{ matrix.board }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Install Checked out PsychicHttp
        run: pio lib -g install -f $GITHUB_WORKSPACE

      - name: Build example 
        run:
          |
          cd examples/${{ matrix.example }}
          cp src/secret.h src/_secret.h
          PIO_BOARD=${{ matrix.board }} PIO_PLATFORM="https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10-rc1/platform-espressif32.zip" pio run -e ci
         # pio run -e ${{ matrix.board }}

      #- run: PIO_BOARD=${{ matrix.board }} PIO_PLATFORM="https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10-rc1/platform-espressif32.zip" pio run -e ci    
